--암호화 복호화
CREATE OR REPLACE PACKAGE PKG_ENCRYPT_DECRYPT
IS
	FUNCTION ENCRYPT(V_INPUT_STRING IN VARCHAR2,
					V_KEY IN VARCHAR2 := 'KHJAVA301' )
	RETURN RAW;
	FUNCTION DECRYPT(V_INPUT_STRING IN VARCHAR2
	,V_KEY IN VARCHAR2 := 'KHJAVA301')
	RETURN VARCHAR2;
END PKG_ENCRYPT_DECRYPT;