CREATE OR REPLACE PACKAGE BODY PKG_ENCRYPT_DECRYPT
IS
	V_KEY_RAW RAW(64);
FUNCTION ENCRYPT(V_INPUT_STRING IN VARCHAR2 ,V_KEY IN VARCHAR2 := 'KHJAVA301')  
RETURN RAW
IS
	V_ORIGINAL_RAW  RAW(64);
	V_ENCRYTED_RAW  RAW(64);
BEGIN 
	V_ORIGINAL_RAW := UTL_I18N.STRING_TO_RAW(V_INPUT_STRING,'AL32UTF8'); 
	V_KEY_RAW := UTL_I18N.STRING_TO_RAW(V_KEY,'AL32UTF8');
	V_ENCRYTED_RAW := DBMS_CRYPTO.ENCRYPT
							( src => V_ORIGINAL_RAW             
							,typ => DBMS_CRYPTO.DES_CBC_PKCS5
							,key => V_KEY_RAW
							,iv => NULL);
	RETURN V_ENCRYTED_RAW;
END ENCRYPT;

FUNCTION DECRYPT(V_INPUT_STRING IN VARCHAR2 ,V_KEY IN VARCHAR2 := 'KHJAVA301')
return varchar2
is
	V_DECRYPTED_RAW      VARCHAR2(64); 
	V_DECRYPTED_CHAR    VARCHAR2(64); 
BEGIN
	V_KEY_RAW := UTL_I18N.STRING_TO_RAW(V_KEY,'AL32UTF8');  
       
	V_DECRYPTED_RAW := DBMS_CRYPTO.DECRYPT(
			src => V_INPUT_STRING
			,typ => DBMS_CRYPTO.DES_CBC_PKCS5
			,key => V_KEY_RAW
			,iv => NULL);
        
	V_DECRYPTED_CHAR := UTL_I18N.RAW_TO_CHAR(V_DECRYPTED_RAW, 'AL32UTF8');
	RETURN V_DECRYPTED_CHAR;
END DECRYPT;

END PKG_ENCRYPT_DECRYPT;